development:
  adapter: postgresql
  encoding: unicode
  database: migration_marathon_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: migration_marathon_test
  pool: 5
  username:
  password:
